#ifndef __IMAP_SYSMGR_H__
#define __IMAP_SYSMGR_H__

/*system manager control reg: RTC*/
#define SYS_RTC_EVENT          (RTC_SYSM_ADDR + 0x0)
#define SYS_RTC_INTCLR         (RTC_SYSM_ADDR + 0x4)
#define SYS_RTC_INTSTAT        (RTC_SYSM_ADDR + 0x8)
#define SYS_RTC_INTMSK         (RTC_SYSM_ADDR + 0xC)
#define SYS_RTC_RESETSTS       (RTC_SYSM_ADDR + 0x10)
#define SYS_RTC_RSTCLR         (RTC_SYSM_ADDR + 0x14)
#define SYS_RTC_OSC_0          (RTC_SYSM_ADDR + 0x18)
#define SYS_RTC_OSC_1          (RTC_SYSM_ADDR + 0x1c)
#define SYS_RTC_PWRSTS         (RTC_SYSM_ADDR + 0x20)
#define SYS_RTC_PWRSTSCLR      (RTC_SYSM_ADDR + 0x24)
#define SYS_RTC_WAKMSK         (RTC_SYSM_ADDR + 0x28)
#define SYS_RTC_INFO0          (RTC_SYSM_ADDR + 0x2C)
#define SYS_RTC_INFO1          (RTC_SYSM_ADDR + 0x30)
#define SYS_RTC_INFO2          (RTC_SYSM_ADDR + 0x34)
#define SYS_RTC_INFO3          (RTC_SYSM_ADDR + 0x38)
#define SYS_RTC_INFO4          (RTC_SYSM_ADDR + 0x3C)
#define SYS_RTC_INFO5          (RTC_SYSM_ADDR + 0x40)
#define SYS_RTC_INFO6          (RTC_SYSM_ADDR + 0x44)
#define SYS_RTC_INFO7          (RTC_SYSM_ADDR + 0x48)
#define SYS_RTC_INFO(x)        (RTC_SYSM_ADDR + (x * 4) + 0x2C)
#define SYS_RTC_GPMODE         (RTC_SYSM_ADDR + 0x4C)
#define SYS_RTC_GPOUTPUT1      (RTC_SYSM_ADDR + 0x50)
#define SYS_RTC_GPPULL         (RTC_SYSM_ADDR + 0x54)
#define SYS_RTC_GPINPUT        (RTC_SYSM_ADDR + 0x58)
#define SYS_RTC_EXTINT1        (RTC_SYSM_ADDR + 0x5C)
#define SYS_POWMASK            (RTC_SYSM_ADDR + 0x60)
#define SYS_ALARM_SEC0         (RTC_SYSM_ADDR + 0x64)
#define SYS_ALARM_SEC1         (RTC_SYSM_ADDR + 0x68)
#define SYS_ALARM_SEC2         (RTC_SYSM_ADDR + 0x6C)
#define SYS_ALARM_WEEK0        (RTC_SYSM_ADDR + 0x70)
#define SYS_ALARM_WEEK1        (RTC_SYSM_ADDR + 0x74)
#define SYS_ALARM_WEN          (RTC_SYSM_ADDR + 0x78)
#define SYS_RTC_GPOUTPUT0      (RTC_SYSM_ADDR + 0x7C)
#define SYS_RTC_SEC0           (RTC_SYSM_ADDR + 0x80)
#define SYS_RTC_SEC1           (RTC_SYSM_ADDR + 0x84)
#define SYS_RTC_SEC2           (RTC_SYSM_ADDR + 0x88)
#define SYS_RTC_SECWEN         (RTC_SYSM_ADDR + 0x8C)
#define SYS_RTC_WEEK0          (RTC_SYSM_ADDR + 0x90)
#define SYS_RTC_WEEK1          (RTC_SYSM_ADDR + 0x94)
#define SYS_RTC_WEEKWEN        (RTC_SYSM_ADDR + 0x98)
#define SYS_RTC_MSEC0          (RTC_SYSM_ADDR + 0x9C)
#define SYS_RTC_MSEC1          (RTC_SYSM_ADDR + 0xA0)
#define SYS_RTC_MSECWEN        (RTC_SYSM_ADDR + 0xA4)
#define SYS_RTC_SECR0          (RTC_SYSM_ADDR + 0xA8)
#define SYS_RTC_SECR1          (RTC_SYSM_ADDR + 0xAC)
#define SYS_RTC_SECR2          (RTC_SYSM_ADDR + 0xB0)
#define SYS_RTC_WEEKR0         (RTC_SYSM_ADDR + 0xB4)
#define SYS_RTC_WEEKR1         (RTC_SYSM_ADDR + 0xB8)
#define SYS_RTC_MSECR0         (RTC_SYSM_ADDR + 0xBC)
#define SYS_RTC_MSECR1         (RTC_SYSM_ADDR + 0xC0)
#define SYS_RTC_EXTINT2        (RTC_SYSM_ADDR + 0x140)
#define SYS_RTC_ADDINTSTAT     (RTC_SYSM_ADDR + 0x144)
#define SYS_RTC_CLEAR          (RTC_SYSM_ADDR + 0x148)
#define SYS_RTC_POWUP_TIMING   (RTC_SYSM_ADDR + 0x15c)
#define SYS_RTC_POWEDGE_IRQ    (RTC_SYSM_ADDR + 0x160)
#define SYS_RTC_LPWCNT         (RTC_SYSM_ADDR + 0x1c4)
#define SYS_RTC_POWDOWN_TIMING (RTC_SYSM_ADDR + 0x1c8)
#define SYS_RTC_POWINTR_TIMING (RTC_SYSM_ADDR + 0x1cc)

/*for sysm ioctl*/
#define SYS_RTC_SEC_SET       (0X80)
#define SYS_RTC_MSEC_SET      (0X81)
#define SYS_RTC_WEEK_SET      (0X82)
#define SYS_RTC_UPDATE        (0X83)
#define SYS_ALARM_SEC_SET     (0X84)
#define SYS_ALARM_WEEK_SET    (0X85)
#define SYS_ALARM_UPDATE      (0X86)
#define SYS_RTC_WEEK_READ     (0X87)
#define SYS_RTC_SEC_READ      (0X88)
#define SYS_RTC_MSEC_READ     (0X89)
#define SYS_SLEEP_SET         (0X8A)
#define SYS_SHUTDOWN_SET      (0X8B)
#define SYS_POLARITY_SET      (0X8C)
#define SYS_POLARITY_UPDATE   (0X8D)
#define SYS_WAKEUP_SOURCE_SET (0X8E)
#define SYS_POW_MASK          (0X8F)
#define SYS_INT_CLEAR         (0X90)
#define SYS_INT_READ          (0X91)
#define SYS_POWUPST_READ      (0X92)
#define SYS_POWUPST_CLEAR     (0X93)
#define SYS_RESETST_READ      (0X94)
#define SYS_RESETST_CLEAR     (0X95)
#define SYS_POWIND_MASK       (0X96)
#define SYS_CHARGE_MASK       (0X97)
#define SYS_POWIND_UNMASK     (0X98)
#define SYS_CHARGE_UNMASK     (0X99)
#define SYS_GPIO_CFG          (0X9A)
#define SYS_GPIO_PULL         (0X9B)
#define SYS_GPIO_WRITE        (0X9C)
#define SYS_GPIO_READ         (0X9D)
#define SYS_GPIO_UPDATE       (0X9E)
#define SYS_IOINTR_MASK       (0X9F)
#define SYS_OSC_SET           (0XA0)
#define SYS_INT_MASK          (0XA1)
#define SYS_ALARM_DISABLE     (0XA2)
#define SYS_GET_INFO_0        (0XA3)
#define SYS_GET_INFO_1        (0XA4)
#define SYS_GET_INFO_2        (0XA5)
#define SYS_GET_INFO_3        (0XA6)
#define SYS_SOFTRESET_SET     (0XA7)
#define SYS_SET_INFO_0        (0XA8)
#define SYS_RTC_POWERUP       (0XA9)
#define SYS_INT_UNMASK        (0XAA)
#define SYS_GET_POWMASK       (0XAB)

/*for socv test*/
#define WAKEUP_EINT0 (0X1)
#define WAKEUP_EINT1 (0X2)
#define WAKEUP_EINT2 (0X4)
#define WAKEUP_EINT3 (0X8)
#define WAKEUP_RTC   (0X10)
#define WAKEUP_EINT4 (0X20)
#define WAKEUP_EINT5 (0X40)

#define WAKE_EINT5  (0x1 << 7)
#define WAKE_EINT4  (0x1 << 6)
#define WAKE_POWKEY (0x1 << 5)
#define WAKE_RTC    (0x1 << 4)
#define WAKE_EINT3  (0x1 << 3)
#define WAKE_EINT2  (0x1 << 2)
#define WAKE_EINT1  (0x1 << 1)
#define WAKE_EINT0  (0x1 << 0)

#define EINT_0 (1)
#define EINT_1 (2)
#define EINT_2 (4)
#define EINT_3 (8)
#define EINT_4 (0x10)
#define EINT_5 (0x20)

#define TRI_BY_LOW  (1)
#define TRI_BY_HIGH (0)

#define IO_INPUT_MODE  (1)
#define IO_OUTPUT_MODE (0)
#define IO_PULL_DOWN   (0)
#define IO_PULL_UP     (1)

#define RESET_POWER_FLAG  (1 << 0)
#define RESET_WAKEUP_FLAG (1 << 1)

#define SLEEP_IRQ     (1 << 0)
#define SHUTDOWN_IRQ  (1 << 1)
#define POWERWARN_IRQ (1 << 2)
#define RTCGP0_IRQ    (1 << 3)
#define RTCGP1_IRQ    (1 << 4)
#define RTCGP2_IRQ    (1 << 5)
#define RTCGP3_IRQ    (1 << 6)
#define RTCGP4_IRQ    (1 << 0)
#define RTCGP5_IRQ    (1 << 1)
#define RTCALARM_IRQ  (1 << 7)
#define POSEDGE_IRQ   (1 << 0)
#define NEGEDGE_IRQ   (1 << 1)

/*rtc irq ID*/
#define RTC_GP0_IRQ      213
#define RTC_GP1_IRQ      214
#define RTC_GP2_IRQ      215
#define RTC_GP3_IRQ      208
#define RTC_MODE_IRQ     209
#define RTC_SLEEP_IRQ    210
#define RTC_SHUTDOWN_IRQ 211
#define RTC_POWWARN_IRQ  212
#define RTC_POWMODE_IRQ  216

#endif /* __IMAP_SYSMGR_H__ */
