#ifndef MAP_SYSTEM_MEMORY_H
#define MAP_SYSTEM_MEMORY_H

#define EMAC_REG_BASE_ADDRESS0      ITCS_C_GMAC0_BASE
#define EMAC_REG_BASE_ADDRESS1      ITCS_C_GMAC1_BASE
#define EMAC_REG_BASE_ADDRESS2      ITCS_C_GMAC2_BASE
#define EMAC_REG_BASE_ADDRESS3      ITCS_S_GMAC3_BASE


#endif
