#define ENTER_ACTIVE_POWER_DOWN                                                     0x3
#define ENTER_ACTIVE_POWER_DOWN_WITH_MEMORY_CLOCK_GATING                            0x13
#define ENTER_PRE_CHARGE_POWER_DOWN                                                 0x5
#define ENTER_PRE_CHARGE_POWER_DOWN_WITH_MEMORY_CLOCK_GATING                        0x25
#define ENTER_SELF_REFRESH_POWER_DOWN_SHORT                                         0x9
#define ENTER_SELF_REFRESH_POWER_DOWN_SHORT_WITH_MEMORY_CLOCK_GATING                0x29
#define ENTER_SELF_REFRESH_POWER_DOWN_LONG                                          0x11
#define ENTER_SELF_REFRESH_POWER_DOWN_LONG_WITH_MEMORY_CLOCK_GATING                 0x31
#define ENTER_SELF_REFRESH_POWER_DOWN_LONG_WITH_MEMORY_AND_CONTROLLER_CLOCK_GATING  0x51
#define EXIT_ANY_LOW_POWER_STATE                                                    0x2
#define ENTER_SELF_REFRESH_SHORT                                                    0x1