#define JTAG_ENABLE                 0x200
#define JTAG_ENABLE_IE              0x204
#define JTAG_ENABLE_OE              0x208
#define JTAG_ENABLE_DRIVE           0x20C
#define JTAG_ENABLE_TERM            0x210


#define JTAG_DATAOUT_ADDRESS        0x214
#define JTAG_DATAOUT_ADDRESS_OE     0x218
#define JTAG_DATAOUT_ADDR_DRIVE     0x21C
#define JTAG_DATAOUT_ADDR_DRIVE2    0x220
#define JTAG_DATAOUT_ADDR_TERM      0x224


#define JTAG_DATAOUT_TSEL_ADDR_EN   0x228
#define JTAG_DATAOUT_TSEL_ADDR_SEL0 0x22C
#define JTAG_DATAOUT_TSEL_ADDR_SEL1 0x230
#define JTAG_DATAOUT_TSEL_ADDR_SEL2 0x234
#define JTAG_DATAOUT_TSEL_ADDR_SEL3 0x238
#define JTAG_DATAOUT_TSEL_ADDR_SEL4 0x23C
#define JTAG_DATAOUT_TSEL_ADDR_SEL5 0x240
#define JTAG_DATAOUT_TSEL_ADDR_SEL6 0x244
#define JTAG_DATAOUT_TSEL_ADDR_SEL7 0x248


#define JTAG_DATAOUT_CS_N           0x24C
#define JTAG_DATAOUT_CS_N_OE        0x250
#define JTAG_DATAOUT_CKE            0x254
#define JTAG_DATAOUT_CKE_OE         0x258
#define JTAG_DATAOUT_RESET_N        0x25C
#define JTAG_DATAOUT_RESET_N_OE     0x260


#define JTAG_DATAOUT_MEM_CLK_0      0x264
#define JTAG_DATAOUT_MEM_CLK_0_OE   0x268
#define JTAG_DATAOUT_MEM_CLK_1      0x26C
#define JTAG_DATAOUT_MEM_CLK_1_OE   0x270
#define JTAG_DATAOUT_CLK_DRIVE      0x274
#define JTAG_DATAOUT_CLK_DRIVE2     0x278
#define JTAG_DATAOUT_CLK_TERM       0x27C

#define JTAG_DATAOUT_DATA           0x280
#define JTAG_DATAOUT_DATA_OE        0x284
#define JTAG_DATAOUT_DATA_DRIVE     0x288
#define JTAG_DATAOUT_DATA_DRIVE2    0x28C
#define JTAG_DATAOUT_DATA_TERM      0x290


#define JTAG_DATAOUT_TSEL_EN        0x294
#define JTAG_DATAOUT_TSEL_WR_SEL0   0x298
#define JTAG_DATAOUT_TSEL_WR_SEL1   0x29C
#define JTAG_DATAOUT_TSEL_WR_SEL2   0x2A0
#define JTAG_DATAOUT_TSEL_WR_SEL3   0x2A4
#define JTAG_DATAOUT_TSEL_WR_SEL4   0x2A8
#define JTAG_DATAOUT_TSEL_WR_SEL5   0x2AC
#define JTAG_DATAOUT_TSEL_WR_SEL6   0x2B0
#define JTAG_DATAOUT_TSEL_WR_SEL7   0x2B4


#define JTAG_DATAOUT_DQS            0x2B8
#define JTAG_DATAOUT_DQS_OE         0x2BC
#define JTAG_DATAOUT_DQS_DRIVE      0x2C0
#define JTAG_DATAOUT_DQS_DRIVE2     0x2C4
#define JTAG_DATAOUT_DQS_TERM       0x2C8


#define JTAG_DATAOUT_DM             0x2CC
#define JTAG_DATAOUT_DM_OE          0x2D0

#define JTAG_DATAIN_ADDRESS         0x2d4       
#define JTAG_DATAOUT_ADDRESS_IE     0x2d8 

#define JTAG_DATAIN_CS_N            0x2dc  
#define JTAG_DATAOUT_CS_N_IE        0x2e0  
#define JTAG_DATAIN_CKE             0x2e4 
#define JTAG_DATAOUT_CKE_IE         0x2e8 
#define JTAG_DATAIN_RESET_N         0x2ec
#define JTAG_DATAOUT_RESET_N_IE     0x2f0

    
#define JTAG_DATAIN_MEM_CLK_0       0x2f4
#define JTAG_DATAIN_MEM_CLK_1       0x2f8 
#define JTAG_DATAOUT_MEM_CLK_0_IE   0x2fc
#define JTAG_DATAOUT_MEM_CLK_1_IE   0x300

#define JTAG_DATAIN_DATA                0x304
#define JTAG_DATAOUT_DATA_IE            0x308
#define JTAG_DATAOUT_DATA_RX_IE_CAL_ALL 0x30c 
#define JTAG_DATAOUT_PHY_RX_CAL_CODE   0x310

#define JTAG_DATAOUT_TSEL_RD_SEL0  0x314
#define JTAG_DATAOUT_TSEL_RD_SEL1  0x318
#define JTAG_DATAOUT_TSEL_RD_SEL2  0x31c
#define JTAG_DATAOUT_TSEL_RD_SEL3  0x320
#define JTAG_DATAOUT_TSEL_RD_SEL4  0x324
#define JTAG_DATAOUT_TSEL_RD_SEL5  0x328
#define JTAG_DATAOUT_TSEL_RD_SEL6  0x32c
#define JTAG_DATAOUT_TSEL_RD_SEL7  0x330

#define JTAG_DATAIN_DQS                 0x334
#define JTAG_DATAOUT_DQS_IE             0x338     
#define JTAG_DATAOUT_DQS_RX_IE_CAL_ALL  0x33c 

#define JTAG_DATAIN_DM                  0x340
#define JTAG_DATAOUT_DM_IE              0x344
#define JTAG_DATAOUT_DM_RX_IE_CAL_ALL   0x348 