ARCHIVE := drv_lpddr4.a

srcs-y += \
	lpddr4_axi_base_test.c \
	lpddr4_axi_priority.c \
	lpddr4_boundary_test.c \
	lpddr4_rtl_common.c \
	lpddr4_dfi_update.c \
	lpddr4_dfs.c \
	lpddr4_dll_bist.c \
	lpddr4_loopback.c \
	lpddr4_lowpower.c \
	lpddr4_manual_loopback_training.c \
	lpddr4_manual_training.c \
	lpddr4_manual_training_low_freq.c \
	lpddr4_mc_init.c \
	lpddr4_phy_init.c \
	lpddr4_phy_pll_bypass.c \
	lpddr4_pi_training.c \
	lpddr4_pll_init.c \
	lpddr4_sys_init.c \
	lpddr4_sys_init_low_freq.c \
	lpddr4_sys_init_row_16.c \
	lpddr4_zq_cal.c	\
	lpddr4_mrw.c \
	dma_ctrl.c \
	gn_bust_test.c \
	lpddr4_pi_training_533.c \
	gn_ddr_test.c \
	lpddr4_rambuster.c

