
ARCHIVE := drv_core-q3.a

CUSTOM_CFLAGS += -I./aarch64 -I.
CUSTOM_AFLAGS += -I./aarch64 -I.
srcs-y += \
	   irq/default_vector.c		\
	   irq/irq-gic.c	\
	   timer-a53.c \
	   serial_imapx800.c \
	   start.S
