/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_SD4HC_REGS_H_
#define REG_SD4HC_REGS_H_

#include <cps_drv.h>

#include "sd4hc_hrs.h"
#include "sd4hc_srs.h"
#include "sd4hc_crs.h"
#include "sd4hc_cqrs.h"

typedef struct __attribute__((packed)) SD4HC_Regs_s {
    SD4HC_Hrs HRS;
    volatile char pad__0[0x150U];
    SD4HC_Srs SRS;
    volatile char pad__1[0x7CU];
    SD4HC_Crs CRS;
    volatile char pad__2[0x100U];
    SD4HC_Cqrs CQRS;
} SD4HC_Regs;

#endif /* REG_SD4HC_REGS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

