/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_SRS_H_
#define REG_SRS_H_

#include <cps_drv.h>

#include "sd4hc_srs_macros.h"

typedef struct __attribute__((packed)) SD4HC_Srs_s {
        volatile uint32_t SRS00;
        volatile uint32_t SRS01;
        volatile uint32_t SRS02;
        volatile uint32_t SRS03;
        volatile uint32_t SRS04;
        volatile uint32_t SRS05;
        volatile uint32_t SRS06;
        volatile uint32_t SRS07;
        volatile uint32_t SRS08;
        volatile uint32_t SRS09;
        volatile uint32_t SRS10;
        volatile uint32_t SRS11;
        volatile uint32_t SRS12;
        volatile uint32_t SRS13;
        volatile uint32_t SRS14;
        volatile uint32_t SRS15;
        volatile uint32_t SRS16;
        volatile uint32_t SRS17;
        volatile uint32_t SRS18;
        volatile uint32_t SRS19;
        volatile uint32_t SRS20;
        volatile uint32_t SRS21;
        volatile uint32_t SRS22;
        volatile uint32_t SRS23;
        volatile uint32_t SRS24;
        volatile uint32_t SRS25;
        volatile uint32_t SRS26;
        volatile uint32_t SRS27;
        volatile char pad__0[0x8U];
        volatile uint32_t SRS30;
        volatile uint32_t SRS31;
} SD4HC_Srs;

#endif /* REG_SRS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

