/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_HRS_H_
#define REG_HRS_H_

#include <cps_drv.h>

#include "sd4hc_hrs_macros.h"

typedef struct __attribute__((packed)) SD4HC_Hrs_s {
        volatile uint32_t HRS00;
        volatile uint32_t HRS01;
        volatile uint32_t HRS02;
        volatile uint32_t HRS03;
        volatile uint32_t HRS04;
        volatile uint32_t HRS05;
        volatile uint32_t HRS06;
        volatile uint32_t HRS07;
        volatile uint32_t HRS08;
        volatile uint32_t HRS09;
        volatile uint32_t HRS10;
        volatile uint32_t HRS11;
        volatile uint32_t HRS12;
        volatile uint32_t HRS13;
        volatile uint32_t HRS14;
        volatile char pad__0[0x4U];
        volatile uint32_t HRS16;
        volatile char pad__1[0x30U];
        volatile uint32_t HRS29;
        volatile uint32_t HRS30;
        volatile uint32_t HRS31;
        volatile uint32_t HRS32;
        volatile uint32_t HRS33;
        volatile uint32_t HRS34;
        volatile char pad__2[0x4U];
        volatile uint32_t HRS36;
        volatile char pad__3[0xCU];
        volatile uint32_t HRS40;
        volatile uint32_t HRS41;
        volatile uint32_t HRS42;
        volatile uint32_t HRS43;
} SD4HC_Hrs;

#endif /* REG_HRS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

