/* parasoft-begin-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names, DRV-4756" */
/* parasoft-begin-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names, DRV-4756" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_SD4HC_CRS_MACROS_H_
#define REG_SD4HC_CRS_MACROS_H_

#define SD4HC__CRS__CRS63_READ_MASK                                  0xFFFFFFFFU
#define SD4HC__CRS__CRS63_WRITE_MASK                                 0xFFFFFFFFU
#define SD4HC__CRS__CRS63__ISES_MASK                                 0x00000001U
#define SD4HC__CRS__CRS63__ISES_SHIFT                                         0U
#define SD4HC__CRS__CRS63__ISES_WIDTH                                         1U
#define SD4HC__CRS__CRS63__ISES_WOCLR                                         0U
#define SD4HC__CRS__CRS63__ISES_WOSET                                         0U
#define SD4HC__CRS__CRS63__RSVD_0_MASK                               0x0000FFFEU
#define SD4HC__CRS__CRS63__RSVD_0_SHIFT                                       1U
#define SD4HC__CRS__CRS63__RSVD_0_WIDTH                                      15U
#define SD4HC__CRS__CRS63__SVN_MASK                                  0x00FF0000U
#define SD4HC__CRS__CRS63__SVN_SHIFT                                         16U
#define SD4HC__CRS__CRS63__SVN_WIDTH                                          8U
#define SD4HC__CRS__CRS63__RSVD_1_MASK                               0xFF000000U
#define SD4HC__CRS__CRS63__RSVD_1_SHIFT                                      24U
#define SD4HC__CRS__CRS63__RSVD_1_WIDTH                                       8U

#endif /* REG_SD4HC_CRS_MACROS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-5_4_b_c99-2 "C99 - similar names, DRV-4756" */
/* parasoft-end-suppress MISRA2012-RULE-5_4_b_c90-2 "C90 - similar names, DRV-4756" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_b_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_b_c90-2 "C90 - limits, DRV-4754" */

