/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_CQRS_H_
#define REG_CQRS_H_

#include <cps_drv.h>

#include "sd4hc_cqrs_macros.h"

typedef struct __attribute__((packed)) SD4HC_Cqrs_s {
        volatile uint32_t CQRS00;
        volatile uint32_t CQRS01;
        volatile uint32_t CQRS02;
        volatile uint32_t CQRS03;
        volatile uint32_t CQRS04;
        volatile uint32_t CQRS05;
        volatile uint32_t CQRS06;
        volatile uint32_t CQRS07;
        volatile uint32_t CQRS08;
        volatile uint32_t CQRS09;
        volatile uint32_t CQRS10;
        volatile uint32_t CQRS11;
        volatile uint32_t CQRS12;
        volatile uint32_t CQRS13;
        volatile uint32_t CQRS14;
        volatile char pad__0[0x4U];
        volatile uint32_t CQRS16;
        volatile uint32_t CQRS17;
        volatile uint32_t CQRS18;
        volatile char pad__1[0x4U];
        volatile uint32_t CQRS20;
        volatile uint32_t CQRS21;
        volatile uint32_t CQRS22;
        volatile uint32_t CQRS23;
} SD4HC_Cqrs;

#endif /* REG_CQRS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

