#ifndef __INTERRUPT_H__
#define __INTERRUPT_H__

#include <common.h>

#ifdef CONFIG_COMPILE_SIM
typedef enum IRQn {
  NMI_EXPn              = -2, /* NMI Exception */
  Machine_Software_IRQn = 3,
  User_Timer_IRQn       = 4, /* User timer interrupt */
  Supervisor_Timer_IRQn = 5,
  CORET_IRQn            = 7,
  Machine_External_IRQn = 11,
  UART_IRQn             = 16, /* uart Interrupt */
  TIM0_IRQn             = 18, /* timer0 Interrupt */
  TIM1_IRQn             = 19, /* timer1 Interrupt */
  TIM2_IRQn             = 20, /* timer2 Interrupt */
  TIM3_IRQn             = 21, /* timer3 Interrupt */
  GPIO4_IRQn            = 27, /* gpio4 Interrupt */
  GPIO5_IRQn            = 28, /* gpio5 Interrupt */
  GPIO6_IRQn            = 29, /* gpio6 Interrupt */
  GPIO7_IRQn            = 30, /* gpio7 Interrupt */
  STIM0_IRQn            = 31, /* stimer0 Interrupt */
  STIM1_IRQn            = 32, /* stimer1 Interrupt */
  STIM2_IRQn            = 33, /* stimer2 Interrupt */
  STIM3_IRQn            = 34, /* stimer3 Interrupt */
  PAD_IRQn              = 35, /* pad Interrupt */
  TIM6_IRQn             = 36, /* timer6 Interrupt */
  TIM7_IRQn             = 37, /* timer7 Interrupt */
  TIM8_IRQn             = 38, /* timer8 Interrupt */
  TIM9_IRQn             = 39, /* timer9 Interrupt */
  TIM10_IRQn            = 40, /* timer10 Interrupt */
  TIM11_IRQn            = 41, /* timer11 Interrupt */
  IIC0_IRQn             = 16,
  IIC1_IRQn,
  IIC2_IRQn,
  IIC3_IRQn,
  IIC4_IRQn,
  IIC5_IRQn,
  CUART0_IRQn = 24,
  CUART1_IRQn,
  CUART2_IRQn,
  CUART3_IRQn,
  DUART0_IRQn,
  DUART1_IRQn,
  DUART2_IRQn,
  DUART3_IRQn,
  SPI0_IRQn,
  SPI1_IRQn,
  SPI2_IRQn,
  SPI3_IRQn,
  IIS0_IRQn,
  IIS1_IRQn,
  TIMER0_IRQn = 40,
  TIMER1_IRQn,
  TIMER2_IRQn,
  TIMER3_IRQn,
  WDT0_IRQn,
  WDT1_IRQn,
  WDT2_IRQn,
  WDT3_IRQn,
  WDT4_IRQn,
  PWM0_IRQn = 50,
  PWM1_IRQn,
  PWM2_IRQn,
  PWM3_IRQn,
  PWM4_IRQn,
  PWM5_IRQn,
  PWM6_IRQn,
  PWM7_IRQn,
  GPIO0_IRQn,
  GPIO1_IRQn,
  GPIO2_IRQn,
  GPIO3_IRQn,
  RTC_IRQn,
  RTC_CHANGE_IRQn,
  EMMC0_IRQn = 66,
  SD1_IRQn,
  SD2_IRQn,
  XSPI0_IRQn,
  XSPI1_IRQn,
  XSPI0_COMP_IRQn,
  XSPI1_COMP_IRQn,
  USB0_REQ0_IRQn = 74,
  USB0_REQ1_IRQn,
  USB0_REQ2_IRQn,
  USB0_REQ3_IRQn,
  USB0_REQ4_IRQn,
  USB0_REQ5_IRQn,
  USB0_REQ6_IRQn,
  USB0_REQ7_IRQn,
  USB0_IRQS0_IRQn,
  USB0_IRQS1_IRQn,
  USB0_OTG_IRQn,
  USB0_PHY_IRQn,
  USB0_HOSTERR_IRQn,
  USB1_REQ0_IRQn,
  USB1_REQ1_IRQn,
  USB1_REQ2_IRQn,
  USB1_REQ3_IRQn,
  USB1_REQ4_IRQn,
  USB1_REQ5_IRQn,
  USB1_REQ6_IRQn,
  USB1_REQ7_IRQn,
  USB1_IRQS0_IRQn,
  USB1_IRQS1_IRQn,
  USB1_OTG_IRQn,
  USB1_PHY_IRQn,
  USB1_HOSTERR_IRQn,
  USB2_REQ0_IRQn,
  USB2_REQ1_IRQn,
  USB2_REQ2_IRQn,
  USB2_REQ3_IRQn,
  USB2_REQ4_IRQn,
  USB2_REQ5_IRQn,
  USB2_REQ6_IRQn,
  USB2_REQ7_IRQn,
  USB2_IRQS0_IRQn,
  USB2_IRQS1_IRQn,
  USB2_OTG_IRQn,
  USB2_PHY_IRQn,
  USB2_HOSTERR_IRQn,
  USB3_REQ0_IRQn,
  USB3_REQ1_IRQn,
  USB3_REQ2_IRQn,
  USB3_REQ3_IRQn,
  USB3_REQ4_IRQn,
  USB3_REQ5_IRQn,
  USB3_REQ6_IRQn,
  USB3_REQ7_IRQn,
  USB3_IRQS0_IRQn,
  USB3_IRQS1_IRQn,
  USB3_OTG_IRQn,
  USB3_PHY_IRQn,
  USB3_HOSTERR_IRQn,
  DMA0_IRQn,
  DMA1_IRQn,
  GMAC0_IRQn,
  GMAC0_Q_IRQn,
  GMAC0_EMAC_IRQn,
  GMAC0_MMSL_IRQn,
  GMAC1_IRQn,
  GMAC1_Q_IRQn,
  GMAC1_EMAC_IRQn,
  GMAC1_MMSL_IRQn,
  MU_CPU0_IRQn = 144,
  MU_CPU1_IRQn,
  MAX_IRQn,

} IRQn_Type;
#else
typedef enum IRQn {
  Supervisor_Software_IRQn = 1,
  Machine_Software_IRQn    = 3,
  Supervisor_Timer_IRQn    = 5,
  CORET_IRQn               = 7,
  Supervisor_External_IRQn = 9,
  Machine_External_IRQn    = 11,
  S_WDT_IRQn               = 16,
  S_GPIO0_IRQn,
  S_GPIO1_IRQn,
  S_TTC0_TIMER0_IRQn = 19,
  S_TTC0_TIMER1_IRQn,
  S_TTC0_TIMER2_IRQn,
  S_SPI0_IRQn,
  S_IIC0_IRQn,
  S_IIC1_IRQn,
  S_UART0_IRQn,
  S_UART1_IRQn,
  S_MU_A2B_IRQn,
  S_MU_B2A_IRQn,
  S_PWM0_IRQn  = 30,
  C_IIC6_IRQn = 32,
  C_IIC7_IRQn,
  C_DMIC0_IRQn,
  C_DMIC1_IRQn,
  C_DMIC2_IRQn,
  C_DMIC3_IRQn,
  S_PUFCC_IRQn = 40,
  S_GMAC3_Q_IRQn,
  S_GMAC3_E_M_IRQn,
  S_GMAC3_WOL_IRQn,
  RTC12_IRQn   = 47, // rtc real-time changed
  RTC0_IRQn,         // rtc gpio3/rtckey
  RTC1_IRQn,         // rtc alm wakeup
  RTC2_IRQn,         // rtc sleep
  RTC3_IRQn,         // rtc shut down
  RTC4_IRQn,         // rtc real-time
  RTC5_IRQn,         // rtc gpio 0
  RTC6_IRQn,         // rtc gpio 1
  RTC7_IRQn,         // rtc gpio 2
  RTC8_IRQn,         // rtc gpio 4
  RTC9_IRQn,         // rtc gpio 5
  RTC10_IRQn,        // rtc pwm
  RTC11_IRQn,
  C_WDT_IRQn,
  C_GPIO0_IRQn,
  C_GPIO1_IRQn,
  C_GPIO2_IRQn,
  C_GPIO3_IRQn,
  C_GPIO4_IRQn,
  C_MIIS0_IRQn,
  C_UART4_IRQn,
  C_UART5_IRQn,
  C_TTC0_TIMER0_IRQn = 69,
  C_TTC0_TIMER1_IRQn,
  C_TTC0_TIMER2_IRQn,
  C_TTC1_TIMER0_IRQn,
  C_TTC1_TIMER1_IRQn,
  C_TTC1_TIMER2_IRQn,
  C_SPI1_IRQn,
  C_SPI2_IRQn,
  C_SPI3_IRQn,
  C_IIC2_IRQn,
  C_IIC3_IRQn,
  C_IIC4_IRQn,
  C_IIC5_IRQn,
  C_UART2_IRQn,
  C_UART3_IRQn,
  C_MU_A2B_IRQn,
  C_MU_B2A_IRQn,
  C_IIS0_IRQn,
  C_IIS1_IRQn,
  C_PWM0_IRQn,
  C_PWM1_IRQn,
  C_PWM2_IRQn,
  C_PWM3_IRQn,
  C_PWM4_IRQn,
  C_PWM5_IRQn,
  C_PWM6_IRQn,
  C_PWM7_IRQn,
  C_PVT0_IRQn,
  C_PVT1_IRQn,
  C_PVT2_IRQn,
  C_PVT3_IRQn,
  C_MPU0_IRQn,
  C_MPU1_IRQn,
  C_GMAC2_WOL_IRQn,
  C_IDS_IRQn,
  C_USB0_CMB0_IRQn = 104,
  C_USB0_CMB1_IRQn,
  C_USB1_CMB0_IRQn,
  C_USB1_CMB1_IRQn,
  C_USB2_CMB0_IRQn,
  C_USB2_CMB1_IRQn,
  C_USB3_CMB0_IRQn,
  C_USB3_CMB1_IRQn,
  C_GMAC0_Q_IRQn = 112,
  C_GMAC0_E_M_IRQn,
  C_GMAC0_WOL_IRQn,
  C_GMAC1_Q_IRQn,
  C_GMAC1_E_M_IRQn,
  C_GMAC1_WOL_IRQn,
  C_GMAC2_Q_IRQn,
  C_GMAC2_E_M_IRQn,
  C_EMMC0_IRQn = 120,
  C_SD0_WKUP_IRQn,
  C_XSPI0_IRQn,
  C_SD1_IRQn,
  C_SD1_WKUP_IRQn,
  C_SD2_IRQn,
  C_SD2_WKUP_IRQn,
  C_XSPI1_IRQn,
  C_CAE0_IRQn,
  C_CAE1_IRQn,
  C_CAE2_IRQn,
  C_CAE3_IRQn,
  C_CAE4_IRQn,
  C_DMA0_IRQn,
  C_DMA1_IRQn,
  C_VENC_IRQn,
  C_VDEC_IRQn,
  C_UART6_IRQn     = 138,
  C_UART7_IRQn,
  C_UART8_IRQn,
  C_UART9_IRQn,
  C_UART10_IRQn,
  C_UART11_IRQn,
  C_USB0_HOST_IRQn = 144,
  C_USB0_DEVICE_IRQn,
  C_USB0_OTG_IRQn,
  C_USB0_PHYPOWER_IRQn,
  C_USB1_HOST_IRQn = 144,
  C_USB1_DEVICE_IRQn,
  C_USB1_OTG_IRQn,
  C_USB1_PHYPOWER_IRQn,
  C_USB2_HOST_IRQn = 144,
  C_USB2_DEVICE_IRQn,
  C_USB2_OTG_IRQn,
  C_USB2_PHYPOWER_IRQn,
  C_USB3_HOST_IRQn = 144,
  C_USB3_DEVICE_IRQn,
  C_USB3_OTG_IRQn,
  C_USB3_PHYPOWER_IRQn,
  C_CAE5_IRQn = 160,
  C_CAE6_IRQn,
  C_CAE7_IRQn,
  C_CAE8_IRQn,
  C_CAE9_IRQn,
  C_NPU0_IRQn,
  C_NPU1_IRQn,
  MAX_IRQn,
} IRQn_Type;

#endif

#endif
