/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_XSPI_REGS_H_
#define REG_XSPI_REGS_H_

#include <cps_drv.h>

#include "xspi_regs_macros.h"

typedef struct __attribute__((packed)) XSPI_Regs_s {
    volatile uint32_t cmd_reg0;
    volatile uint32_t cmd_reg1;
    volatile uint32_t cmd_reg2;
    volatile uint32_t cmd_reg3;
    volatile uint32_t cmd_reg4;
    volatile uint32_t cmd_reg5;
    volatile char pad__0[0x28U];
    volatile uint32_t cmd_status_ptr;
    volatile uint32_t cmd_status;
    volatile char pad__1[0xB8U];
    volatile uint32_t ctrl_status;
    volatile uint32_t trd_status;
    volatile char pad__2[0x8U];
    volatile uint32_t intr_status;
    volatile uint32_t intr_enable;
    volatile char pad__3[0x8U];
    volatile uint32_t trd_comp_intr_status;
    volatile char pad__4[0xCU];
    volatile uint32_t trd_error_intr_status;
    volatile uint32_t trd_error_intr_en;
    volatile char pad__5[0x18U];
    volatile uint32_t dma_target_error_l;
    volatile uint32_t dma_target_error_h;
    volatile uint32_t boot_status;
    volatile char pad__6[0xA4U];
    volatile char pad__7[0x8U];
    volatile uint32_t long_polling;
    volatile uint32_t short_polling;
    volatile char pad__8[0x20U];
    volatile uint32_t ctrl_config;
    volatile char pad__9[0x8U];
    volatile uint32_t dma_settings;
    volatile uint32_t sdma_size;
    volatile uint32_t sdma_trd_info;
    volatile char pad__10[0x4U];
    volatile uint32_t sdma_addr0;
    volatile uint32_t sdma_addr1;
    volatile char pad__11[0xCU];
    volatile uint32_t discovery_control;
    volatile char pad__12[0x11CU];
    volatile char pad__13[0x8U];
    volatile uint32_t xip_mode_cfg;
    volatile char pad__14[0x4U];
    volatile uint32_t global_seq_cfg;
    volatile uint32_t global_seq_cfg_1;
    volatile uint32_t direct_access_cfg;
    volatile uint32_t direct_access_rmp;
    volatile uint32_t direct_access_rmp_1;
    volatile char pad__15[0x5CU];
    volatile uint32_t rst_seq_cfg_0;
    volatile uint32_t rst_seq_cfg_1;
    volatile uint32_t rst_seq_cfg_2;
    volatile char pad__16[0x4U];
    volatile uint32_t ers_seq_cfg_0;
    volatile uint32_t ers_seq_cfg_1;
    volatile uint32_t ers_seq_cfg_2;
    volatile char pad__17[0x4U];
    volatile uint32_t prog_seq_cfg_0;
    volatile uint32_t prog_seq_cfg_1;
    volatile uint32_t prog_seq_cfg_2;
    volatile char pad__18[0x4U];
    volatile uint32_t read_seq_cfg_0;
    volatile uint32_t read_seq_cfg_1;
    volatile uint32_t read_seq_cfg_2;
    volatile char pad__19[0x4U];
    volatile uint32_t we_seq_cfg_0;
    volatile char pad__20[0xCU];
    volatile uint32_t stat_seq_cfg_0;
    volatile uint32_t stat_seq_cfg_1;
    volatile uint32_t stat_seq_cfg_2;
    volatile uint32_t stat_seq_cfg_3;
    volatile uint32_t stat_seq_cfg_4;
    volatile uint32_t stat_seq_cfg_5;
    volatile char pad__21[0x4U];
    volatile uint32_t stat_seq_cfg_7;
    volatile uint32_t stat_seq_cfg_8;
    volatile uint32_t stat_seq_cfg_9;
    volatile uint32_t stat_seq_cfg_10;
    volatile char pad__22[0xA84U];
    volatile uint32_t xspi_ctrl_version;
    volatile uint32_t ctrl_features_reg;
    volatile char pad__23[0xF8U];
    volatile uint32_t wp_settings;
    volatile uint32_t reset_pin_settings;
    volatile uint32_t clock_mode_settings;
    volatile uint32_t jedec_rst_timing_reg;
    volatile uint32_t dev_delay_reg;
    volatile uint32_t rst_recovery_reg;
    volatile uint32_t dev_active_max_reg;
    volatile char pad__24[0x4U];
    volatile uint32_t hf_offset_reg;
    volatile char pad__25[0x4U];
    /* no_dll_phy_reg register is used only in IOT config */
    volatile uint32_t no_dll_phy_reg;
    volatile char pad__26[0x4U];
    volatile uint32_t dll_phy_update_cnt;
    volatile uint32_t dll_phy_ctrl;
} XSPI_Regs;

#endif /* REG_XSPI_REGS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

