deps_config := \
	arch/riscv/lib/Kconfig \
	arch/riscv/e902/Kconfig \
	arch/riscv/e906/Kconfig \
	arch/riscv/c906/Kconfig \
	arch/riscv/c920/Kconfig \
	arch/riscv/Kconfig \
	arch/arm/q3/Kconfig \
	arch/arm/Kconfig \
	arch/Kconfig \
	lib/sbi/Kconfig \
	lib/freertos/Kconfig \
	lib/rtl/Kconfig \
	lib/rtlfs/Kconfig \
	lib/fatfs/Kconfig \
	lib/interrupt/Kconfig \
	lib/common/Kconfig \
	lib/crypto/Kconfig \
	lib/console/Kconfig \
	lib/stdlib/Kconfig \
	lib/shell/Kconfig \
	lib/math/Kconfig \
	lib/command/Kconfig \
	lib/Kconfig \
	testbench/hwmon/Kconfig \
	testbench/dmic_pcm/Kconfig \
	testbench/fatfs/Kconfig \
	testbench/pmic/Kconfig \
	testbench/venc/Kconfig \
	testbench/dmic/Kconfig \
	testbench/npu/Kconfig \
	testbench/ids/Kconfig \
	testbench/lpddr4/Kconfig \
	testbench/rxa/Kconfig \
	testbench/ddr/Kconfig \
	testbench/pufcc/Kconfig \
	testbench/cae/Kconfig \
	testbench/pvt/Kconfig \
	testbench/pwm/Kconfig \
	testbench/mu/Kconfig \
	testbench/xspi/Kconfig \
	testbench/spi/Kconfig \
	testbench/rtc/Kconfig \
	testbench/drd/Kconfig \
	testbench/sysm/Kconfig \
	testbench/sdmmc/Kconfig \
	testbench/vdec/Kconfig \
	testbench/i2s/Kconfig \
	testbench/eth/Kconfig \
	testbench/uart/Kconfig \
	testbench/wdt/Kconfig \
	testbench/task/Kconfig \
	testbench/skull/Kconfig \
	testbench/i2c/Kconfig \
	testbench/timer/Kconfig \
	testbench/rtlfs/Kconfig \
	testbench/irq/Kconfig \
	testbench/dma/Kconfig \
	testbench/cpu/Kconfig \
	testbench/Kconfig \
	drivers/hwmon/Kconfig \
	drivers/dmic_pcm/Kconfig \
	drivers/pmic/Kconfig \
	drivers/venc/Kconfig \
	drivers/dmic/Kconfig \
	drivers/ids/Kconfig \
	drivers/vdec/Kconfig \
	drivers/lpddr4/Kconfig \
	drivers/rxa/Kconfig \
	drivers/ddr/Kconfig \
	drivers/pufcc/Kconfig \
	drivers/cae/Kconfig \
	drivers/pvt/Kconfig \
	drivers/pwm/Kconfig \
	drivers/mu/Kconfig \
	drivers/spi_flash/Kconfig \
	drivers/xspi/Kconfig \
	drivers/spi/Kconfig \
	drivers/rtc/Kconfig \
	drivers/drd/Kconfig \
	drivers/sdmmc/Kconfig \
	drivers/i2s/es8388/Kconfig \
	drivers/i2s/Kconfig \
	drivers/eth/Kconfig \
	drivers/uart/Kconfig \
	drivers/wdt/Kconfig \
	drivers/eeprom/microchip_24aa08/Kconfig \
	drivers/eeprom/Kconfig \
	drivers/i2c/Kconfig \
	drivers/timer/Kconfig \
	drivers/irqchip/Kconfig \
	drivers/sysm/Kconfig \
	drivers/dma/Kconfig \
	drivers/Kconfig \
	/home/intchains/project/bms/bms/Kconfig

/home/intchains/project/bms/bms/include/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
