/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754"
 * parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754"
 */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding
 * implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2021 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_USB_SSP_DRD_REGS_H_
#define REG_USB_SSP_DRD_REGS_H_

#include <cps_drv.h>

#include "usb_ssp_drd_regs_macros.h"

typedef struct __attribute__((packed)) USB_SspDrdRegs_s {
  volatile uint32_t CDNS_DID;
  volatile uint32_t CDNS_RID;
  volatile uint32_t OTGCAPABILITY;
  volatile char pad__0[0x4U];
  volatile uint32_t OTGCMD;
  volatile uint32_t OTGSTS;
  volatile uint32_t OTGSTATE;
  volatile char pad__1[0x4U];
  volatile uint32_t OTGIEN;
  volatile uint32_t OTGIVECT;
  volatile uint32_t CLK_FREQ;
  volatile uint32_t OTGTMR;
  volatile char pad__2[0x10U];
  volatile uint32_t OTGSIMULATE;
  volatile uint32_t OVERRIDE;
  volatile uint32_t SUSP_CTRL;
  volatile char pad__3[0x4U];
  volatile uint32_t OTGANASTS;
  volatile uint32_t ADP_RAMP_TIME;
  volatile uint32_t OTGCTRL1;
  volatile uint32_t OTGCTRL2;
  volatile uint32_t VBUSVALID_DBNC_CFG;
  volatile uint32_t SESSVALID_DBNC_CFG;
  volatile uint32_t IDDIG_DBNC_CFG;
  volatile char pad__4[0x20U];
  volatile uint32_t DB_ASF_MEM_MASK;
} USB_SspDrdRegs;

#endif /* REG_USB_SSP_DRD_REGS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of
 * structure, DRV-3667" */
