ARCHIVE := testbench_ids.a


ifdef CONFIG_TBH_IDS_MEDIA
srcs-y += \
	lcd-main.c \
	osd-main.c \
	cvbs-main.c \
	media-main.c \
	idsapi-main.c
else
srcs-y += \
	lcd-main.c \
	osd-main.c \
	cvbs-main.c \
	idsapi-main.c
endif
