/* parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-begin-suppress item MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

/**********************************************************************
 * Copyright (C) 2014-2020 Cadence Design Systems, Inc.
 * All rights reserved worldwide
 * The material contained herein is the proprietary and confidential
 * information of Cadence or its licensors, and is supplied subject to, and may
 * be used only by Cadence's customer in accordance with a previously executed
 * license and maintenance agreement between Cadence and that customer.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_CCP_REGS_H_
#define REG_CCP_REGS_H_

#include <cps_drv.h>

#include "ccp_regs_macros.h"

typedef struct __attribute__((packed)) CCP_Regs_s {
    volatile char pad__0[0x2000U];
    volatile uint32_t phy_dq_timing_reg;
    volatile uint32_t phy_dqs_timing_reg;
    volatile uint32_t phy_gate_lpbk_ctrl_reg;
    volatile uint32_t phy_dll_master_ctrl_reg;
    volatile uint32_t phy_dll_slave_ctrl_reg;
    volatile uint32_t phy_ie_timing_reg;
    volatile uint32_t phy_obs_reg_0;
    volatile uint32_t phy_dll_obs_reg_0;
    volatile uint32_t phy_dll_obs_reg_1;
    volatile uint32_t phy_dll_obs_reg_2;
    volatile uint32_t phy_static_togg_reg;
    volatile uint32_t phy_wr_deskew_reg;
    volatile uint32_t phy_wr_rd_deskew_cmd_reg;
    volatile uint32_t phy_wr_deskew_pd_ctrl_0_reg;
    volatile uint32_t phy_wr_deskew_pd_ctrl_1_reg;
    volatile uint32_t phy_rd_deskew_reg;
    volatile char pad__1[0x34U];
    volatile uint32_t phy_features_reg;
    volatile char pad__2[0x8U];
    volatile uint32_t phy_ctrl_reg;
    volatile uint32_t phy_tsel_reg;
    volatile uint32_t phy_gpio_ctrl_0;
    volatile uint32_t phy_gpio_ctrl_1;
    volatile uint32_t phy_gpio_status_0;
    volatile uint32_t phy_gpio_status_1;
} CCP_Regs;

#endif /* REG_CCP_REGS_H_ */

/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits, DRV-4754" */
/* parasoft-end-suppress MISRA2012-DIR-4_8 "Consider hiding implementation of structure, DRV-3667" */

