#ifndef __LPDDR4_H__
#define __LPDDR4_H__

#define MA_OUTW(a,b) writel((b), (a))
#define MA_INW(a) readl((a))

extern void lpddr4_init(int port);

enum {
	DDRAPP_TEST_MPU0,
	DDRAPP_TEST_MPU1,
	LPDDR4_PI_TEST,
	LPDDR4_1066MHZ_TEST,
	LPDDR4_PHY_LOOPBACK_TEST,
	LPDDR4_PHY_PLL_BYPASS_TEST,
	LPDDR4_PHY_DLL_MBIST_TEST,
	LPDDR4_AXI_TEST,
	LPDDR4_LOW_POWER_TEST,
	LPDDR4_DFS_TEST,
	LPDDR4_ZQ_CAL_TEST,
	LPDDR4_AXI_PRIORITY_TEST,
	LPDDR4_JTAG_BOUNDARY_TEST,
	LPDDR4_MODE_REG_TEST,
	LPDDR4_BIST_MARCH_C_TEST,
	LPDDR4_BIST_PRBS_TEST,
	LPDDR4_MULTI_PORT_PARALLEL_TEST,
	LPDDR4_MEMTESTER_TEST_MPU0,
	LPDDR4_MEMTESTER_TEST_MPU1,
	RAMBUSTER_TEST
};

#endif
